---
name: k8s-testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  k3d-tesing:
    name: Kubernets CI testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          k3d-args: --agents 2 --wait
      - name: Get Kubernets cluster details
        run: |
          kubectl version --short
          kubectl cluster-info
          ubectl get nodes
