---
name: Lint code base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # FILTER_REGEX_EXCLUDE: .*md
